### ISSUE TITLE
We need to change the username and password in index.js

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/couchdb-superlogin-docker#2]
Hi,

The couchdb superlogin works without changing the username and password but if u need to make a POST or GET request we need to keep username and password same as in docker-compose.yml file

**Comment by salus-sage** [comment]
That's the idea right in providing the environment variables through docker-compose and pass it to the code and not keep changing the code everytime there is any change. 
And index js should not have any pwd credentials, it should be process.env.COUCHDB_USER and so on..
